services:

  db:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - 8080:80
